torchrun --nproc_per_node=3 train_without_sft.py \
    --model_name_or_path alpaca-7b-wdiff \
    --data_path data/alpaca_formatted_train_debug.json \
    --fp16 True \
    --output_dir alpaca_run \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 